verbose: true
go:
    version: 1.17
    cgo: false
repository:
    path: github.com/pascomnet/kamailio_exporter
build:
    flags: -a -tags netgo
    ldflags: |
        -s
        -X main.Version={{.Version}}
        -X main.Revision={{.Revision}}
        -X main.Branch={{.Branch}}
        -X main.BuildUser={{user}}@{{host}}
        -X main.BuildDate={{date "20060102-15:04:05"}}
tarball:
    prefix: .
    files:
        - LICENSE
crossbuild:
    platforms:
        - linux/amd64
        - linux/arm64
        - darwin/amd64
        - darwin/arm64
