---
version: 2

jobs:
  test:
    docker:
    - image: circleci/golang:1.17

    steps:
    - checkout
    - run: make promu
    - run: make style build
    - run: rm -fv kamailio_exporter

  build:
    machine: true

    steps:
    - checkout
    - run: make promu
    - run: promu crossbuild -v
    - persist_to_workspace:
        root: .
        paths:
        - .build
    - store_artifacts:
        path: .build
        destination: /build

  release_tags:
    docker:
    - image: circleci/golang:1.17

    steps:
    - checkout
    - run: mkdir -v -p ${HOME}/bin
    - run: curl -L 'https://github.com/github-release/github-release/releases/download/v0.10.0/linux-amd64-github-release.bz2' | tar xvjf - --strip-components 3 -C ${HOME}/bin
    - run: echo 'export PATH=${HOME}/bin:${PATH}' >> ${BASH_ENV}
    - attach_workspace:
        at: .
    - run: make promu
    - run: promu crossbuild tarballs
    - run: promu checksum .tarballs
    - run: promu release .tarballs
    - store_artifacts:
        path: .tarballs
        destination: releases

workflows:
  version: 2
  kamailio_exporter:
    jobs:
    - test:
        filters:
          tags:
            only: /.*/
    - build:
        filters:
          tags:
            only: /.*/
    - release_tags:
        requires:
        - test
        - build
        filters:
          tags:
            only: /^v[0-9]+(\.[0-9]+){2}(-.+|[^-.]*)$/
          branches:
            ignore: /.*/
